### ISSUE TITLE
Checking if user is part of group in ldap

### ISSUE THREAD

**Issue by jperry** [cschiewek/devise_ldap_authenticatable#110]
Hi,

I was able to get the authentication working against a user in ldap but then I wanted to also verify the user is part of a particular group.  I looked at the ldap.yml file and looked at the authorizations part and configured to what I think is correct.  Here is a sample of what I have:

```
authorizations: &AUTHORIZATIONS
  group_base: ou=Groups,dc=company,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["memberuid", "cn=devsupport,ou=Groups,dc=company,dc=com"]
```

The "memberuid" is an attribute under the devsupport group.  I was able to find my user when grouping these two seaches and an ldap.search using the net/ldap gem.  See below:

```
filter_group = Net::LDAP::Filter.eq("cn", "devsupport")
filter_user = Net::LDAP::Filter.contains("memberuid", "jperry")
# Combine the filters into one
filter = filter_group & filter_user
treebase = "dc=company,dc=com"

```

The output looks something like this:

```
DN: cn=devsupport,ou=Groups,dc=company,dc=com
   dn:
      --->cn=devsupport,ou=Groups,dc=company,dc=com
   gidnumber:
      --->2001
   objectclass:
      --->posixGroup
      --->top
   cn:
      --->devsupport
   memberuid:
      --->jperry
      --->jsmith
```

Am I doing something wrong here as I'm getting the failure below when I try to login using devise ldap.  Apologies if any of this is confusing. 

```
Completed 500 Internal Server Error in 1806ms

Net::LDAP::LdapError (Invalid binding information):
  net-ldap (0.2.2) lib/net/ldap.rb:1224:in `bind_simple'
  net-ldap (0.2.2) lib/net/ldap.rb:1203:in `bind'
  net-ldap (0.2.2) lib/net/ldap.rb:712:in `bind'
```

Thanks,
Jay
