### ISSUE TITLE
ssl connection reset

### ISSUE THREAD

**Issue by chewmanfoo** [cschiewek/devise_ldap_authenticatable#115]
I keep getting connection reset by peer when using Devise ldap_authenticatable:

``` ruby
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"secret", "user"=>{"username"=>"sg0218049", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Sign in"}
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`username` = 'sg0218049' LIMIT 1
  LDAP: LDAP dn lookup: cn=sg0218049
  LDAP: LDAP search for login: cn=sg0218049
Completed 500 Internal Server Error in 939ms

Errno::ECONNRESET (Connection reset by peer - SSL_connect):
```

Is there something I can tweak in the configs to fix this?

**Comment by sarink** [comment]
@hmark6 
````
Devise.setup do |config|
  config.ldap_config = "#{Rails.root}/config/ldap.yml"
````
and here's a sample ldap.yml...
````
production:
  host: yourhost
  port: 389
  attribute: sAMAccountName
  base: dc=yourdc
  admin_user: <%= Rails.application.secrets.ldap_admin_user %>
  admin_password: <%= Rails.application.secrets.ldap_admin_password %>
  ssl: false
````
the answer to your question is the last line of the config: ``ssl: false``
