### ISSUE TITLE
undefined method `[]' for nil:NilClass when attempting to log in

### ISSUE THREAD

**Issue by tmarkey** [cschiewek/devise_ldap_authenticatable#155]
This error is driving me slowly crazy: 
NoMethodError in Devise::SessionsController#create
undefined method `[]' for nil:NilClass

I've been unable to determine what the issue could be. I've migrated my db changes, restarted my app and ensured permissions are correct on my files. I've pored over message boards looking for someone with this issue to no avail. Worse, I've got it working correctly on another server and after careful comparison, have no clue what the difference between my two implementations is. I'm operating on CentOS 6.4 with nginx+passenger phusion+rails. Here is as much information as I can think of, but I'll happily provide more if someone can help with this

<b>development.log of the working server</b>

```
Started POST "/users/sign_in" for 24.38.84.170 at 2013-12-31 13:29:47 -0500
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"â", "authenticity_token"=>"VDmsykTfyaGxPEl3Zg2zv2FeL+4dZ98qONbQXcfPo7I=", "user"=>{"email"=>"test@test.com", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}
  User Load (0.6ms)  SELECT `users`.* FROM `users` WHERE `users`.`email` = 'test@test.com' ORDER BY `users`.`id` ASC LIMIT 1
  LDAP: LDAP dn lookup: mail=test@test.com
  LDAP: LDAP search for login: mail=test@test.com
  LDAP: LDAP search yielded 1 matches
  LDAP: Authorizing user CN=Test User,OU=IT,OU=Company,OU=Users,OU=Location,DC=srx,DC=com
  LDAP: LDAP dn lookup: mail=test@test.com
  LDAP: LDAP search for login: mail=test@test.com
  LDAP: LDAP search yielded 1 matches
   (0.2ms)  BEGIN
  SQL (0.5ms)  UPDATE `users` SET `last_sign_in_at` = '2013-11-20 21:15:48', `current_sign_in_at` = '2013-12-31 18:29:47', `last_sign_in_ip` = '24.38.84.170', `sign_in_count` = 14, `updated_at` = '2013-12-31 18:29:47' WHERE `users`.`id` = 1
   (27.0ms)  COMMIT
Redirected to https://pf_app/
Completed 302 Found in 98ms (ActiveRecord: 28.2ms)
```

<b>development.log of the server with the error</b>

```
Started POST "/users/sign_in" for 24.38.84.170 at 2013-12-31 15:59:24 -0500
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"â", "authenticity_token"=>"8WF7SN/e/ijwI6piqwlaow73yw8UUy662lb5KnRBsEo=", "user"=>{"email"=>"test@test.com", "password"=>"[FILTERED]"}, "commit"=>"Sign in"}
  User Load (0.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`email` = 'test@test.com' ORDER BY `users`.`id` ASC LIMIT 1
Completed 500 Internal Server Error in 7ms
```

<b>Full Trace</b>

```
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/ldap/connection.rb:9:in `initialize'
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/ldap/adapter.rb:14:in `new'
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/ldap/adapter.rb:14:in `valid_credentials?'
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/model.rb:48:in `valid_ldap_authentication?'
activesupport (4.0.2) lib/active_support/core_ext/object/try.rb:45:in `public_send'
activesupport (4.0.2) lib/active_support/core_ext/object/try.rb:45:in `try'
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/model.rb:98:in `authenticate_with_ldap'
devise_ldap_authenticatable (0.8.1) lib/devise_ldap_authenticatable/strategy.rb:7:in `authenticate!'
warden (1.2.3) lib/warden/strategies/base.rb:53:in `_run!'
warden (1.2.3) lib/warden/proxy.rb:354:in `block in _run_strategies_for'
warden (1.2.3) lib/warden/proxy.rb:349:in `each'
warden (1.2.3) lib/warden/proxy.rb:349:in `_run_strategies_for'
warden (1.2.3) lib/warden/proxy.rb:319:in `_perform_authentication'
warden (1.2.3) lib/warden/proxy.rb:127:in `authenticate!'
devise (3.2.2) app/controllers/devise/sessions_controller.rb:15:in `create'
actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.2) lib/active_support/callbacks.rb:443:in `_run__1358810453395053371__process_action__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.2) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.2) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.2) lib/action_dispatch/routing/mapper.rb:44:in `call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.2) lib/active_record/migration.rb:369:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__3671196738146640893__call__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.0.2) lib/rails/engine.rb:511:in `call'
railties (4.0.2) lib/rails/application.rb:97:in `call'
passenger (4.0.29) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
passenger (4.0.29) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
passenger (4.0.29) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
passenger (4.0.29) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'
```

<b>ldap.yml</b>

```
## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    # cn=admins,ou=groups,dc=test,dc=com
    # cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    # ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

  ## Environment
  development:
    host: [DC FQDN]
    port: 389
    attribute: mail
    base: ou=Location,dc=srx,dc=com
    admin_user: [USERNAME@srx.com]
    admin_password: [PW]
    ssl: false
    # <<: *AUTHORIZATIONS

  test:
    host: [DC FQDN]
    port: 389
    attribute: mail
    base: ou=Location,dc=srx,dc=com
    admin_user: [USERNAME@srx.com]
    admin_password: [PW]
    ssl: simple_tls
    # <<: *AUTHORIZATIONS

  production:
    host: [DC FQDN]
    port: 389
    attribute: mail
    base: ou=Location,dc=srx,dc=com
    admin_user: [USERNAME@srx.com]
    admin_password: [PW]
    ssl: start_tls
    # <<: *AUTHORIZATIONS
```
