### ISSUE TITLE
Allow multiple LDAP providers

### ISSUE THREAD

**Issue by cms5109** [cschiewek/devise_ldap_authenticatable#176]
I have a requirement to authenticate against two distinct LDAP servers. I've seen some requests for this functionality elsewhere, but didn't find any standard way to implement. 

In order to do this, I configured my ldap.yml to return an array of config values

```
development:
 - 
  host: "ldap.server1.com"
  port: "3268"
  attribute: uid
  base: dc=my-domain,dc=com
  admin_user: cn=admin,dc=my-domain,dc=com
  admin_password: admin_password
  ssl: false
 - 
  host: "ldap.server2.com"
  port: "389"
  attribute: uid
  base: dc=my-domain,dc=com
  admin_user: cn=admin,dc=my-domain,dc=com
  admin_password: admin_password
  ssl: false
```

and then updated ldap/connection.rb to loop through multiple config settings - 

```
ldap_configs = YAML.load(ERB.new(File.read(::Devise.ldap_config || "#{Rails.root}/config/ldap.yml")).result)[Rails.env]
ldap_configs = ldap_configs.is_a?(Hash) ? [ldap_configs] : ldap_configs
ldap_options = params
ldap_configs.each do |ldap_config|
  #initialize connection with ldap_config values
  if @ldap.bind
    puts "Authenticated successfully!"
    break
  else
    puts "User doesn't exist in this connection"
  end
end
```

If this is a useful feature, I can submit a pull request.
