### ISSUE TITLE
Ignore server certificate error

### ISSUE THREAD

**Issue by kuzevanoff** [cschiewek/devise_ldap_authenticatable#253]
Hi,
i have this error:
Net::LDAP::Error (hostname "x.x.x.x" does not match the server certificate):

So I need to ignore certificate error.

How I can do it?
Thanks

**Comment by irruputuncu** [comment]
I had the same error and found these settings to ignore the certificate error in a development environment: 

```
encryption:
  method: simple_tls
  tls_options:
    verify_mode: OpenSSL::SSL::VERIFY_NONE
```
(see also this [stackoverflow question](https://stackoverflow.com/questions/44831666/how-to-tell-ruby-net-ldap-to-ignore-server-cert-hostname-mismatch))

However I had to change the gem a little bit so the config would be read as symbols in order to work with (the newest version) of ruby-net-ldap. I created PR #264 with my alterations. It's still more of a workaround but might already be helpful.
