### ISSUE TITLE
Active Directory howto

### ISSUE THREAD

**Issue by kf0jvt** [cschiewek/devise_ldap_authenticatable#68]
Is anyone willing to share the ldap.yml configuration they use to authenticate against Active Directory?  I have tried to configure devise_ldap_authenticatable with the same configuration that works for me in omniauth-ldap, but I am getting nowhere.  

This is what I am using right now:

```
development:
  host: IP ADDRESS
  port: 389 
  attribute: sAMAccountName 
  base: dc=domain,dc=example,dc=com
  admin_user: cn=User\, Name,cn=Users,dc=domain,dc=example,dc=com 
  admin_password: Password
  ssl: false
  # <<: *AUTHORIZATIONS
```

Right now I just want to allow any user to log in.  I'll worry about group membership after I get over this hurdle.  Also, is there any way to put devise_ldap_authenticatable into a debug mode so I can get more detailed logging?
